{"name": "test_4", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 11", "trace": "@allure.feature(\"模块二\")\n    @allure.story(\"这是一个非常哇塞的用例\")\n    def test_4():\n>       assert 1 == 11\nE       assert 1 == 11\n\ntest_1.py:21: AssertionError"}, "start": 1566181540260, "stop": 1566181540261, "uuid": "08eca974-3115-417a-9541-0076d4ddd2e2", "historyId": "c8cd82c99acc944c4aab84b5eddb6ed6", "fullName": "test_1#test_4", "labels": [{"name": "story", "value": "这是一个非常哇塞的用例"}, {"name": "feature", "value": "模块二"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-3THE6Q3"}, {"name": "thread", "value": "6136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1"}]}